package com.hitk.railwayreservation.model

enum class StationName {
    HOWRAH, KOLKATA, NEW_DELHI, MUMBAI, PATNA, KANPUR, ALLAHABAD, BANGALORE, LUCKNOW, VARANASI, KALYAN, CHENNAI, NAGPUR, GORAKHPUR,
    CUTTACK, JAISALMER, MYSORE, SRINAGAR
}